# Generated by Django 4.2.5 on 2023-09-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=122)),
                ('phoneno', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Postpdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetatt.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('rno', models.CharField(max_length=12)),
                ('mark', models.IntegerField()),
                ('smark', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetatt.folder')),
                ('tid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meetatt.contact')),
            ],
        ),
    ]
