# Generated by Django 3.0.8 on 2021-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetatt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('rno', models.CharField(max_length=12)),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
