# Generated by Django 3.0.8 on 2021-04-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetatt', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=122)),
                ('phoneno', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
