# Generated by Django 3.0.8 on 2021-04-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetatt', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='tid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meetatt.Contact'),
        ),
    ]
