# Generated by Django 3.0.8 on 2021-04-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetatt', '0004_class_tid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='tid',
        ),
    ]
