# Generated by Django 3.0.8 on 2021-05-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetatt', '0006_class_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='smark',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
